
create TABLE client(
    id SERIAL PRIMARY KEY,
    title VARCHAR(255),
    content VARCHAR(255)
);

create TABLE project(
    id SERIAL PRIMARY KEY,
    serial VARCHAR(255), 
    title VARCHAR(255),
    status BOOLEAN,
    comment VARCHAR(255),
    client INTEGER,
    FOREIGN KEY (client) REFERENCES client (id)
);

create TABLE article(
    id SERIAL PRIMARY KEY,
    title VARCHAR(20),
    comment VARCHAR(255)
);

create TABLE bet(
    id SERIAL PRIMARY KEY,
    bet FLOAT,
    normal INTEGER,
    comment VARCHAR(255)
);

create TABLE instruction(
    id SERIAL PRIMARY KEY,
    datetime VARCHAR(255),
    serial VARCHAR(255),
    summary INTEGER,
    article INTEGER,
    project INTEGER,
    bet INTEGER,
    component1_title VARCHAR(255),
    component1_summary INTEGER,
    component2_title VARCHAR(255),
    component2_summary INTEGER,
    FOREIGN KEY (project) REFERENCES project (id),
    FOREIGN KEY (article) REFERENCES article (id),
    FOREIGN KEY (bet) REFERENCES bet (id)
);


create TABLE worker(
    id SERIAL PRIMARY KEY,
    surname VARCHAR(255),
    name VARCHAR(255),
    patron VARCHAR(255),
    bet INTEGER,
    phone INTEGER,
    day BOOLEAN,
    status BOOLEAN,
    recruitor INTEGER,
    comment VARCHAR(255),
    FOREIGN KEY (recruitor) REFERENCES client (id),
    FOREIGN KEY (bet) REFERENCES bet (id)
);

create TABLE shift(
    id SERIAL PRIMARY KEY,
    datetime VARCHAR(255),
    master VARCHAR(255),
    instruction INTEGER,
    statement VARCHAR(255),
    day BOOLEAN,
    done BOOLEAN,
    worker1_name INTEGER,
    worker1_instruction INTEGER,
    worker1_bet INTEGER,
    worker1_start INTEGER,
    worker1_end INTEGER,
    worker1_lunch BOOLEAN,
    worker1_summary INTEGER,
    worker1_type VARCHAR(30),
    FOREIGN KEY (worker1_name) REFERENCES worker (id),
    FOREIGN KEY (worker1_instruction) REFERENCES instruction (id),
    FOREIGN KEY (worker1_bet) REFERENCES bet (id),
    worker2_name INTEGER,
    worker2_instruction INTEGER,
    worker2_bet INTEGER,
    worker2_start INTEGER,
    worker2_end INTEGER,
    worker2_lunch BOOLEAN,
    worker2_summary INTEGER,
    worker2_type VARCHAR(30),
    FOREIGN KEY (worker2_name) REFERENCES worker (id),
    FOREIGN KEY (worker2_instruction) REFERENCES instruction (id),
    FOREIGN KEY (worker2_bet) REFERENCES bet (id),
    worker3_name INTEGER,
    worker3_instruction INTEGER,
    worker3_bet INTEGER,
    worker3_start INTEGER,
    worker3_end INTEGER,
    worker3_lunch BOOLEAN,
    worker3_summary INTEGER,
    worker3_type VARCHAR(30),
    FOREIGN KEY (worker3_name) REFERENCES worker (id),
    FOREIGN KEY (worker3_instruction) REFERENCES instruction (id),
    FOREIGN KEY (worker3_bet) REFERENCES bet (id),
    worker4_name INTEGER,
    worker4_instruction INTEGER,
    worker4_bet INTEGER,
    worker4_start INTEGER,
    worker4_end INTEGER,
    worker4_lunch BOOLEAN,
    worker4_summary INTEGER,
    worker4_type VARCHAR(30),
    FOREIGN KEY (worker4_name) REFERENCES worker (id),
    FOREIGN KEY (worker4_instruction) REFERENCES instruction (id),
    FOREIGN KEY (worker4_bet) REFERENCES bet (id),
    worker5_name INTEGER,
    worker5_instruction INTEGER,
    worker5_bet INTEGER,
    worker5_start INTEGER,
    worker5_end INTEGER,
    worker5_lunch BOOLEAN,
    worker5_summary INTEGER,
    worker5_type VARCHAR(30),
    FOREIGN KEY (worker5_name) REFERENCES worker (id),
    FOREIGN KEY (worker5_instruction) REFERENCES instruction (id),
    FOREIGN KEY (worker5_bet) REFERENCES bet (id),
    worker6_name INTEGER,
    worker6_instruction INTEGER,
    worker6_bet INTEGER,
    worker6_start INTEGER,
    worker6_end INTEGER,
    worker6_lunch BOOLEAN,
    worker6_summary INTEGER,
    worker6_type VARCHAR(30),
    FOREIGN KEY (worker6_name) REFERENCES worker (id),
    FOREIGN KEY (worker6_instruction) REFERENCES instruction (id),
    FOREIGN KEY (worker6_bet) REFERENCES bet (id),
    worker7_name INTEGER,
    worker7_instruction INTEGER,
    worker7_bet INTEGER,
    worker7_start INTEGER,
    worker7_end INTEGER,
    worker7_lunch BOOLEAN,
    worker7_summary INTEGER,
    worker7_type VARCHAR(30),
    FOREIGN KEY (worker7_name) REFERENCES worker (id),
    FOREIGN KEY (worker7_instruction) REFERENCES instruction (id),
    FOREIGN KEY (worker7_bet) REFERENCES bet (id),
    worker8_name INTEGER,
    worker8_instruction INTEGER,
    worker8_bet INTEGER,
    worker8_start INTEGER,
    worker8_end INTEGER,
    worker8_lunch BOOLEAN,
    worker8_summary INTEGER,
    worker8_type VARCHAR(30),
    FOREIGN KEY (worker8_name) REFERENCES worker (id),
    FOREIGN KEY (worker8_instruction) REFERENCES instruction (id),
    FOREIGN KEY (worker8_bet) REFERENCES bet (id),
    worker9_name INTEGER,
    worker9_instruction INTEGER,
    worker9_bet INTEGER,
    worker9_start INTEGER,
    worker9_end INTEGER,
    worker9_lunch BOOLEAN,
    worker9_summary INTEGER,
    worker9_type VARCHAR(30),
    FOREIGN KEY (worker9_name) REFERENCES worker (id),
    FOREIGN KEY (worker9_instruction) REFERENCES instruction (id),
    FOREIGN KEY (worker9_bet) REFERENCES bet (id),
    worker10_name INTEGER,
    worker10_instruction INTEGER,
    worker10_bet INTEGER,
    worker10_start INTEGER,
    worker10_end INTEGER,
    worker10_lunch BOOLEAN,
    worker10_summary INTEGER,
    worker10_type VARCHAR(30),
    FOREIGN KEY (worker10_name) REFERENCES worker (id),
    FOREIGN KEY (worker10_instruction) REFERENCES instruction (id),
    FOREIGN KEY (worker10_bet) REFERENCES bet (id),
    FOREIGN KEY (instruction) REFERENCES instruction (id)
);